name: talkaholic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6
  provider: ^6.1.2
  flutter_pdfview: ^1.3.4
  syncfusion_flutter_pdf: ^27.2.2
  encrypt: ^5.0.0
  clipboard: ^0.1.3
  lottie: ^3.1.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  dash_chat_2: ^0.0.21
  firebase_analytics: ^11.3.3
  google_fonts: ^6.2.1
  delightful_toast: ^1.1.0
  get_it: ^8.0.1
  image_picker: ^1.1.2
  path_provider: ^2.0.8



flutter:
  uses-material-design: true
  assets:
    - assets/giftbox_animation.json
    - assets/bg.png